plugins:
    ara:
        executor: host_agent
        source: https://github.com/szulman/cloudify-ara-plugin/archive/master.zip
        package_name: cloudify-ara-plugin
        package_version: 'master'

node_types:
    # An app module configured with ara
    cloudify.ara.nodes.DemoApp:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.Blah:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.DIMENSIONS_DEMO:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.Applicattion_Pipeline_01:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.Application_Pipeline_02:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.cmb_http_test:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.BOND-1776:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.App_rest2:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.hhhhh:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.Arademo:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.AllWebServers:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.Depl_Mgr:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.ARA_AGENT:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.ARA_DM:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.ARA_AE:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.ARA_AWI:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



    cloudify.ara.nodes.WordPress:
        derived_from: cloudify.nodes.ApplicationModule
        interfaces:
            cloudify.interfaces.lifecycle:
                create:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                configure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                start:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                stop:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                delete:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
        properties:
            ara_config: {}



relationships:
    cloudify.ara.depends_on:
        derived_from: cloudify.relationships.depends_on
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                preconfigure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                postconfigure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                establish:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                unlink:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}


    cloudify.ara.connected_to:
        derived_from: cloudify.relationships.connected_to
        source_interfaces:
            # The comment under types.interfaces applies here too
            cloudify.interfaces.relationship_lifecycle:
                preconfigure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                postconfigure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                establish:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                unlink:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}


    cloudify.ara.contained_in:
        derived_from: cloudify.relationships.connected_to
        source_interfaces:
            # The comment under types.interfaces applies here too
            cloudify.interfaces.relationship_lifecycle:
                preconfigure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                postconfigure:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                establish:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}
                unlink:
                    implementation: ara.ara_plugin.operations.operation
                    inputs: {}

