package com.uc4.importexportservice.structure;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.07.22 at 10:19:21 AM ICT
//


import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MainType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MainType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Package"/>
 *     &lt;enumeration value="Release"/>
 *     &lt;enumeration value="PackageRelation"/>
 *     &lt;enumeration value="Environment"/>
 *     &lt;enumeration value="EnvironmentDeploymentTargetRelation"/>
 *     &lt;enumeration value="Application"/>
 *     &lt;enumeration value="Component"/>
 *     &lt;enumeration value="Workflow"/>
 *     &lt;enumeration value="Stage"/>
 *     &lt;enumeration value="User"/>
 *     &lt;enumeration value="Usergroup"/>
 *     &lt;enumeration value="UserUsergroupRelation"/>
 *     &lt;enumeration value="PackageComponentRelation"/>
 *     &lt;enumeration value="PackageApplicationRelation"/>
 *     &lt;enumeration value="DynamicProperty"/>
 *     &lt;enumeration value="Activity"/>
 *     &lt;enumeration value="ActivityPackageRelation"/>
 *     &lt;enumeration value="Reservation"/>
 *     &lt;enumeration value="ReleaseStageMilestone"/>
 *     &lt;enumeration value="ReleaseApplicationRelation"/>
 *     &lt;enumeration value="PackageDependency"/>
 *     &lt;enumeration value="ComponentLink"/>
 *     &lt;enumeration value="DeploymentProfileTarget"/>
 *     &lt;enumeration value="DeploymentProfileComponentLink"/>
 *     &lt;enumeration value="InstalledPackageComponent"/>
 *     &lt;enumeration value="EnvironmentSnapshot"/>
 *     &lt;enumeration value="EnvironmentSnapshotReport"/>
 *     &lt;enumeration value="DeploymentTargetSnapshot"/>
 *     &lt;enumeration value="DeploymentTargetSnapshotReport"/>
 *     &lt;enumeration value="DeploymentTargetRequirementFilter"/>
 *     &lt;enumeration value="DeploymentTarget"/>
 *     &lt;enumeration value="Folder"/>
 *     &lt;enumeration value="FolderPermission"/>
 *     &lt;enumeration value="LoginObject"/>
 *     &lt;enumeration value="Credential"/>
 *     &lt;enumeration value="DeploymentProfile"/>
 *     &lt;enumeration value="ApprovalRule"/>
 *     &lt;enumeration value="ApprovalRuleCondition"/>
 *     &lt;enumeration value="ApprovalRequest"/>
 *     &lt;enumeration value="ActivityTemplate"/>
 *     &lt;enumeration value="TemplateActivity"/>
 *     &lt;enumeration value="Execution"/>
 *     &lt;enumeration value="ExecutionTemplate"/>
 *     &lt;enumeration value="Queue"/>
 *     &lt;enumeration value="QueueRun"/>
 *     &lt;enumeration value="DeploymentProfileQueueRelation"/>
 *     &lt;enumeration value="WorkflowExecutionTemplate"/>
 *     &lt;enumeration value="PackageStateChangeEvent"/>
 *     &lt;enumeration value="WorkflowDefinition"/>
 *     &lt;enumeration value="CustomAction"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "MainType")
@XmlEnum
public enum MainType {

    @XmlEnumValue("Package")
    PACKAGE("Package"),
    @XmlEnumValue("Release")
    RELEASE("Release"),
    @XmlEnumValue("PackageRelation")
    PACKAGE_RELATION("PackageRelation"),
    @XmlEnumValue("Environment")
    ENVIRONMENT("Environment"),
    @XmlEnumValue("EnvironmentDeploymentTargetRelation")
    ENVIRONMENT_DEPLOYMENT_TARGET_RELATION("EnvironmentDeploymentTargetRelation"),
    @XmlEnumValue("Application")
    APPLICATION("Application"),
    @XmlEnumValue("Component")
    COMPONENT("Component"),
    @XmlEnumValue("Workflow")
    WORKFLOW("Workflow"),
    @XmlEnumValue("Stage")
    STAGE("Stage"),
    @XmlEnumValue("User")
    USER("User"),
    @XmlEnumValue("Usergroup")
    USERGROUP("Usergroup"),
    @XmlEnumValue("UserUsergroupRelation")
    USER_USERGROUP_RELATION("UserUsergroupRelation"),
    @XmlEnumValue("PackageComponentRelation")
    PACKAGE_COMPONENT_RELATION("PackageComponentRelation"),
    @XmlEnumValue("PackageApplicationRelation")
    PACKAGE_APPLICATION_RELATION("PackageApplicationRelation"),
    @XmlEnumValue("DynamicProperty")
    DYNAMIC_PROPERTY("DynamicProperty"),
    @XmlEnumValue("Activity")
    ACTIVITY("Activity"),
    @XmlEnumValue("ActivityPackageRelation")
    ACTIVITY_PACKAGE_RELATION("ActivityPackageRelation"),
    @XmlEnumValue("Reservation")
    RESERVATION("Reservation"),
    @XmlEnumValue("ReleaseStageMilestone")
    RELEASE_STAGE_MILESTONE("ReleaseStageMilestone"),
    @XmlEnumValue("ReleaseApplicationRelation")
    RELEASE_APPLICATION_RELATION("ReleaseApplicationRelation"),
    @XmlEnumValue("PackageDependency")
    PACKAGE_DEPENDENCY("PackageDependency"),
    @XmlEnumValue("ComponentLink")
    COMPONENT_LINK("ComponentLink"),
    @XmlEnumValue("DeploymentProfileTarget")
    DEPLOYMENT_PROFILE_TARGET("DeploymentProfileTarget"),
    @XmlEnumValue("DeploymentProfileComponentLink")
    DEPLOYMENT_PROFILE_COMPONENT_LINK("DeploymentProfileComponentLink"),
    @XmlEnumValue("InstalledPackageComponent")
    INSTALLED_PACKAGE_COMPONENT("InstalledPackageComponent"),
    @XmlEnumValue("EnvironmentSnapshot")
    ENVIRONMENT_SNAPSHOT("EnvironmentSnapshot"),
    @XmlEnumValue("EnvironmentSnapshotReport")
    ENVIRONMENT_SNAPSHOT_REPORT("EnvironmentSnapshotReport"),
    @XmlEnumValue("DeploymentTargetSnapshot")
    DEPLOYMENT_TARGET_SNAPSHOT("DeploymentTargetSnapshot"),
    @XmlEnumValue("DeploymentTargetSnapshotReport")
    DEPLOYMENT_TARGET_SNAPSHOT_REPORT("DeploymentTargetSnapshotReport"),
    @XmlEnumValue("DeploymentTargetRequirementFilter")
    DEPLOYMENT_TARGET_REQUIREMENT_FILTER("DeploymentTargetRequirementFilter"),
    @XmlEnumValue("DeploymentTarget")
    DEPLOYMENT_TARGET("DeploymentTarget"),
    @XmlEnumValue("Folder")
    FOLDER("Folder"),
    @XmlEnumValue("FolderPermission")
    FOLDER_PERMISSION("FolderPermission"),
    @XmlEnumValue("LoginObject")
    LOGIN_OBJECT("LoginObject"),
    @XmlEnumValue("Credential")
    CREDENTIAL("Credential"),
    @XmlEnumValue("DeploymentProfile")
    DEPLOYMENT_PROFILE("DeploymentProfile"),
    @XmlEnumValue("ApprovalRule")
    APPROVAL_RULE("ApprovalRule"),
    @XmlEnumValue("ApprovalRuleCondition")
    APPROVAL_RULE_CONDITION("ApprovalRuleCondition"),
    @XmlEnumValue("ApprovalRequest")
    APPROVAL_REQUEST("ApprovalRequest"),
    @XmlEnumValue("ActivityTemplate")
    ACTIVITY_TEMPLATE("ActivityTemplate"),
    @XmlEnumValue("TemplateActivity")
    TEMPLATE_ACTIVITY("TemplateActivity"),
    @XmlEnumValue("Execution")
    EXECUTION("Execution"),
    @XmlEnumValue("ExecutionTemplate")
    EXECUTION_TEMPLATE("ExecutionTemplate"),
    @XmlEnumValue("Queue")
    QUEUE("Queue"),
    @XmlEnumValue("QueueRun")
    QUEUE_RUN("QueueRun"),
    @XmlEnumValue("DeploymentProfileQueueRelation")
    DEPLOYMENT_PROFILE_QUEUE_RELATION("DeploymentProfileQueueRelation"),
    @XmlEnumValue("WorkflowExecutionTemplate")
    WORKFLOW_EXECUTION_TEMPLATE("WorkflowExecutionTemplate"),
    @XmlEnumValue("PackageStateChangeEvent")
    PACKAGE_STATE_CHANGE_EVENT("PackageStateChangeEvent"),
    @XmlEnumValue("WorkflowDefinition")
    WORKFLOW_DEFINITION("WorkflowDefinition"),
    @XmlEnumValue("CustomAction")
    CUSTOM_ACTION("CustomAction");
    private final String value;

    MainType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MainType fromValue(String v) {
        for (MainType c: MainType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}